### ISSUE TITLE
不知有没有详细使用介绍，或项目实例

### ISSUE THREAD

**Issue by findmoon** [suxf/EasySharpFrame#2]
感觉是一个非常不错的基础库，提供的方法、常见功能挺多，要是有详细使用的实例项目介绍，就更好了

**Comment by suxf** [comment]
谢谢您对这个框架的认可！
[Sample](https://github.com/suxf/ECSharp/tree/master/Sample)文件夹下写了一些的例子，有简单的调试控制台，每个例子也都写了相关用法注释，可以直接运行代码测试。完整案例都是商业项目，没办法提供出来。
